name: Generate schemata

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  gen-schemata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run --features fs
      - run: git diff --quiet || exit 1
